/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2018-03-22 08:36:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


        
        
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Manage HTML Sourced Data</title>\n");
      out.write("    <meta charset=\"utf-8\" />\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/gijgo@1.9.1/combined/css/gijgo.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/gijgo@1.9.1/combined/css/demo.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/gijgo@1.9.1/combined/js/gijgo.min.js\" type=\"text/javascript\"></script>\n");
      out.write("   \n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        /*function x(id, name)\n");
      out.write("        {\n");
      out.write("            $(document).ready(function(){$(\"#div1\").load(\"i?a=\"id+\"&\"+\"b=\"+name);});\n");
      out.write("        }*/\n");
      out.write("        </script>\n");
      out.write("        ");
      out.write("\n");
      out.write("       \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"gj-margin-top-10\">\n");
      out.write("        <div class=\"gj-float-left\">\n");
      out.write("            <form class=\"display-inline\">\n");
      out.write("                <input id=\"txtName\" type=\"text\" placeholder=\"Name...\" class=\"gj-textbox-md gj-display-inline-block gj-width-200\" />\n");
      out.write("                <input id=\"txtPlaceOfBirth\" type=\"text\" placeholder=\"Place Of Birth...\" class=\"gj-textbox-md gj-display-inline-block gj-width-200\" />\n");
      out.write("                <button id=\"btnSearch\" type=\"button\" class=\"gj-button-md\">Search</button>\n");
      out.write("                <button id=\"btnClear\" type=\"button\" class=\"gj-button-md\">Clear</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"gj-float-right\">\n");
      out.write("            <button id=\"btnAdd\" type=\"button\" class=\"gj-button-md\">Add New Record</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"gj-clear-both\"></div>\n");
      out.write("    <div class=\"gj-margin-top-10\">\n");
      out.write("        <table id=\"grid\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th width=\"56\">ID</th>\n");
      out.write("                    <th data-sortable=\"true\">Name</th>\n");
      out.write("                    <th data-field=\"PlaceOfBirth\">Place Of Birth</th>\n");
      out.write("                    <th width=\"64\" data-tmpl=\"<span class='material-icons gj-cursor-pointer'>edit</span>\"align=\"center\" data-events=\"click: Edit\"></th>\n");
      out.write("                    <th width=\"64\" data-tmpl=\"<span class='material-icons gj-cursor-pointer'>delete</span>\" align=\"center\" data-events=\"click: Delete\"></th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("               \n");
      out.write("                    ");
try
            		{
                		
                		Class.forName("com.mysql.jdbc.Driver"); 
                		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/suraj?" +
                                   "user=suraj&password=Sahil1996jena");
                		Statement stmt=con.createStatement();
                		String sql="select * from jena";
                		ResultSet rs = stmt.executeQuery(sql);
                	      while(rs.next()){
                	         String first = rs.getString("id");
                	         String last = rs.getString("name");
      out.write("\n");
      out.write(" <tr>\n");
      out.write("                \t         <td>");
      out.print(first);
      out.write("</td>\n");
      out.write("                \t         <td>");
      out.print(last);
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("                \t      ");
}
                		
                		}catch(Exception e)
                		{
                			out.println(e);
                		} 
      out.write("\n");
      out.write("                    \n");
      out.write("                \n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"dialog\" class=\"gj-display-none\" width=\"360\" data-auto-open=\"false\" data-modal=\"true\">\n");
      out.write("        <div data-role=\"body\">\n");
      out.write("            <input type=\"hidden\" id=\"ID\" />\n");
      out.write("            <div class=\"\">\n");
      out.write("                <input type=\"text\" class=\"gj-textbox-md\" id=\"Name\" placeholder=\"Name...\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"gj-margin-top-20\">\n");
      out.write("                <input type=\"text\" class=\"gj-textbox-md\" id=\"PlaceOfBirth\" placeholder=\"Place Of Birth...\" />\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div data-role=\"footer\">\n");
      out.write("            <button type=\"button\" id=\"btnSave\" class=\"gj-button-md\" onclick=\"change()\">Save</button>\n");
      out.write("            <button type=\"button\" id=\"btnCancel\" class=\"gj-button-md\">Cancel</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("                                <div id=\"div1\"></div>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        var  id;\n");
      out.write("        var name;\n");
      out.write("        var grid, dialog;\n");
      out.write("        function Edit(e) {\n");
      out.write("            $('#ID').val(e.data.record.ID);\n");
      out.write("            $('#Name').val(e.data.record.Name);\n");
      out.write("            $('#PlaceOfBirth').val(e.data.record.PlaceOfBirth);   \n");
      out.write("            dialog.open('Edit Player');\n");
      out.write("           \n");
      out.write("          \n");
      out.write("        }\n");
      out.write("        function Delete(e) {\n");
      out.write("            if (confirm('Are you sure?')) {\n");
      out.write("                grid.removeRow(e.data.id - 1);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function Save() {\n");
      out.write("            if ($('#ID').val()) {\n");
      out.write("                id = parseInt($('#ID').val());\n");
      out.write("                name=$('#Name').val();\n");
      out.write("                grid.updateRow(id, { 'ID': id, 'Name': $('#Name').val(), 'PlaceOfBirth': $('#PlaceOfBirth').val() });\n");
      out.write("                \n");
      out.write("            } else {\n");
      out.write("                grid.addRow({ 'ID': grid.count(true) + 1, 'Name': $('#Name').val(), 'PlaceOfBirth': $('#PlaceOfBirth').val() });\n");
      out.write("            }\n");
      out.write("            dialog.close();\n");
      out.write("        }\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            grid = $('#grid').grid({\n");
      out.write("                primaryKey: 'ID',\n");
      out.write("                pager: { limit: 5 }\n");
      out.write("            });\n");
      out.write("            dialog = $('#dialog').dialog();\n");
      out.write("            $('#btnAdd').on('click', function () {\n");
      out.write("                $('#ID').val('');\n");
      out.write("                $('#Name').val('');\n");
      out.write("                $('#PlaceOfBirth').val('');\n");
      out.write("                dialog.open('Add Player');\n");
      out.write("            });\n");
      out.write("            $('#btnSave').on('click', Save);\n");
      out.write("            $('#btnCancel').on('click', function () {\n");
      out.write("                dialog.close();\n");
      out.write("            });\n");
      out.write("            $('#btnSearch').on('click', function () {\n");
      out.write("                grid.reload({ Name: $('#txtName').val(), PlaceOfBirth: $('#txtPlaceOfBirth').val() });\n");
      out.write("            });\n");
      out.write("            $('#btnClear').on('click', function () {\n");
      out.write("                $('#srcName').val('');\n");
      out.write("                $('#srcPlaceOfBirth').val('');\n");
      out.write("                grid.reload({ Name: '', PlaceOfBirth: '' });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        function change()\n");
      out.write("            {\n");
      out.write("                var x = new service1.CheckListManagementService();\n");
      out.write("                x.addCheckList(id, name);\n");
      out.write("                document.write(id)\n");
      out.write("            }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
